live_config_reload = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x303030"
index = 18

[[colors.indexed_colors]]
color = "0x353535"
index = 19

[[colors.indexed_colors]]
color = "0xb2ccd6"
index = 20

[[colors.indexed_colors]]
color = "0xeeffff"
index = 21

[colors.bright]
black = "0x4a4a4a"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xffffff"
yellow = "0xffcb6b"

[colors.cursor]
cursor = "0xeeffff"
text = "0x212121"

[colors.normal]
black = "0x181a20"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xeeffff"
yellow = "0xffcb6b"

[colors.primary]
background = "0x181a20"
foreground = "0xeeffff"

[cursor]
unfocused_hollow = false

[env]
TERM = "alacritty"

[font]
size = 11.25

[font.offset]
x = 0
y = 0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Extra Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[scrolling]
history = 1000

[window]
#decoration = "none"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 7
y = 7
