#!/usr/bin/zsh
#bspc monitor eDP -d "Web" "Code" "COM" "Doc" "VM" "Game" &
#bspc monitor eDP -r &
xrandr -q | grep -w connected | grep HDMI-0 && xrandr --output HDMI-0 --mode 3840x2160 --primary && bspc monitor HDMI-0 -d "Web" "Code" "COM" "Doc" "VM" "Test" && (pgrep -x ulauncher || ulauncher --no-window) &
bspc rule --remove "*"  # Reset all window rules
#bspc monitor HDMI-1-0 -d "Web" "Code" "COM" "Doc" "VM" "Game" &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst -conf .config/dunst/dunstrc &
setxkbmap -option ctrl:nocaps
#setxkbmap -option keypad:pointerkeys
pgrep -x picom || picom &
#feh --bg-scale ~/.ASUS.JPG
nitrogen --restore &
pgrep -x polkit-gnome-au || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/home/jake/.config/polybar/launch.sh &
pgrep -x fcitx || fcitx &
#alacritty --class 'BG' &
bspc rule -a 'Ulauncher' state=floating layer=above border=off
bspc rule -a 'scrcpy' state=floating
bspc rule -a 'Screenkey' manage=off
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'Google-chrome:crx_cbgkkbaghihhnaeabfcmmglhnfkfnpon' state=floating
bspc rule -a 'Org.gnome.Dictionary' state=floating
#bspc rule -a 'Rofi' state=floating border=off
#bspc rule -a "Wine" border=off state=floating
#bspc rule -a "wechat.exe" border=off state=floating
#bspc rule -a 'Alacritty:BG' state=fullscreen sticky=true layer=below border=off locked=true
bspc config normal_border_color "#6e8a74"
bspc config presel_feedback_color "#6272a4"
bspc config focused_border_color "#c3e88d"

bspc config border_width 3
bspc config window_gap 5
bspc config window_gap 12
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
