#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# fix 4 latte
#bspc config top_padding 22

:'
# auto start
fcitx &
electron-ssr &
picom &
sh -c "(sleep 30 && exec /opt/nutstore/bin/nutstore-pydaemon.py)"  &
/usr/bin/libinput-gestures &
/usr/bin/xsettingsd &
feh --bg-scale ~/Pictures/backgrounds/bg_1.jpg &
python /home/toor/Documents/PycharmProjects/LinuxTools/KBSwitchTray.py &

# polybar
/home/toor/.config/polybar/launch.sh
'
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
