#!/usr/bin/zsh
bspc rule --remove "*"  # Reset all window rules

killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# fix 4 latte
#bspc config top_padding 22
#killall latte-dock
#latte-dock --layout BSPWM &
# auto start
# wmname LG3D &
killall ulauncher
#ulauncher --hide-window --no-window-shadow &
ulauncher --hide-window  &
killall fcitx
fcitx &
killall electron-ssr
electron-ssr &
killall picom
picom &
# sh -c "(sleep 30 && exec /opt/nutstore/bin/nutstore-pydaemon.py)"  &
#/usr/bin/libinput-gestures &
/usr/bin/xsettingsd &
# feh --bg-scale ~/Pictures/backgrounds/bg_1.jpg &
nitrogen --restore &
#python /home/toor/Documents/PycharmProjects/LinuxTools/KBSwitchTray.py &
# mount disk2
udisksctl mount -b /dev/sda4 &

# polybar
#env PATH=${PATH}:/home/toor/Software/taskbar /home/toor/.config/polybar/launch.sh --docky &
/home/toor/.config/polybar/launch.sh --docky &

killall polkit-kde-auth
/usr/lib/polkit-kde-authentication-agent-1 &

#echo $PATH > ~/path &
# taskbar
#taskbar restart &

# tray
tint2 &

bspc monitor -d "I" "II" "III" "IV" "V"

bspc rule -a 'Ulauncher' state=floating layer=above border=off
bspc rule -a 'Screenkey' manage=off
bspc rule -a "Wine" border=off state=floating
bspc config normal_border_color "#676E95"
bspc config active_border_color   "#C792EA"
bspc config focused_border_color  "#C792EA"
bspc config presel_feedback_color "#6272a4"

bspc config border_width 4
bspc config window_gap 8
bspc config top_padding 29
#bspc config left_padding 5
#bspc config right_padding 5
#bspc config bottom_padding 5

#bspc config bottom_monocle_padding -5
#bspc config left_monocle_padding -5
#bspc config right_monocle_padding -5
#bspc config top_monocle_padding -5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
